baseURL = 'https://acbx.eu.org/'
languageCode = 'zh-cn'
timezone = 'Asia/Shanghai'
defaultContentLanguage = 'zh-cn'
theme = 'farallon'


[langusges]

[languages.zh-cn]
  title = "北海轻歌-记录一个城市中的一个人."
  languageName = "简体中文"
  contentDir = 'content/zh-cn'
  [languages.zh-cn.menu]
    [[languages.zh-cn.menu.main]]
    name="自由行"
    url="/category/travel/"
    weight="1"
    [[languages.zh-cn.menu.main]]
    name="书影音"
    url="/movies/"
    weight="3"
    [[languages.zh-cn.menu.main]]
    name="生活记"
    url="/category/zine/"
    weight="2"
    [[languages.zh-cn.menu.main]]
    name="归档页"
    url="/archive/"
    weight="5"

[taxonomies]
  category = 'categories'
  tag = 'tags'

[outputs]
  home = [ "HTML","JSON","RSS","SITEMAP"]
  page = ["HTML"]


[markup.tableOfContents]
  endLevel = 5
  startLevel = 3

[permalinks]
  [permalinks.section]
    post = '/archive'
  [permalinks.page]
    post = '/story/:slugorfilename/'
    page = '/:slugorfilename/'  
  [permalinks.term]
    tags = '/tag/:slug/'
    categories = '/category/:slug/'
  [permalinks.taxonomy]
    tags = '/topics/'
    categories = '/cats/'

[related]
  includeNewer = true
  [[related.indices]]
    applyFilter = false
    cardinalityThreshold = 0
    name = 'tags'
    pattern = ''
    toLower = false
    type = 'basic'
    weight = 80
  [[related.indices]]
    applyFilter = false
    cardinalityThreshold = 0
    name = 'date'
    pattern = ''
    toLower = false
    type = 'basic'
    weight = 10