search= true
description = 'A simple and fast blog framework written in Go.'
toc = true
mainSections = ['post','memo']
indexName = 'bigfa'
searchKey = 'b0825b184f45c084e31770fbcc9261f2'
searchAPPID = 'FX1CAS2SD8'
showAuthor = true
authorName = '北海轻歌'
authorDescription = '社会主义好青年.'
authorAvatar = 'https://img.010316.xyz/1.jpg'
commentDomain = 'https://fatesinger.com/__api/v1'
telegram = 'https://t.me/s/guoran7'
feed = '/index.xml'
twitter = 'https://x.com/chensu'
instagram = 'https://www.instagram.com/guoran_cs/'
github = 'https://github.com/GuoRan18'
footer_sns = true
post_like = true
post_view = true
actionDomain = 'hhttps://twikoo.010316.xyz:2018/'
dbAPIBase = 'https://node.wpista.com/'
zoom= true